"""240420241756

Revision ID: 925b22137838
Revises: 
Create Date: 2024-04-24 17:57:41.994465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925b22137838'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userEmail', sa.String(length=100), nullable=False),
    sa.Column('userName', sa.String(length=50), nullable=False),
    sa.Column('userSurname', sa.String(length=100), nullable=False),
    sa.Column('userKey', sa.String(length=160), nullable=False),
    sa.Column('userLevelAccess', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('userEmail')
    )
    op.create_table('user_history',
    sa.Column('userEmail', sa.String(length=100), nullable=False),
    sa.Column('userStatus', sa.String(length=100), nullable=False),
    sa.Column('userLevelAccess', sa.String(length=100), nullable=False),
    sa.Column('userCreatedBy', sa.String(length=100), nullable=False),
    sa.Column('creationDate', sa.Date(), nullable=False),
    sa.Column('deleteDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('userEmail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_history')
    op.drop_table('user')
    # ### end Alembic commands ###
